//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Compliance {
    
    
    public partial class DefaultPage {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        //public new ASC.Web.Compliance.Masters.BasicTemplate Master {
        //    get {
        //        return ((ASC.Web.Compliance.Masters.BasicTemplate)(base.Master));
        //    }
        //}
    }
}
